/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dias_TP6.vista;

import Diaz_TP6.entidad.Directorio;

/**
 *
 * @author long_
 */
public class viewMenu extends javax.swing.JFrame {
    Directorio directorio;
    /**
     * Creates new form viewMenu
     */
    public viewMenu() {
        initComponents();
        directorio = new Directorio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jmbMenu = new javax.swing.JMenuBar();
        jmEditarCliente = new javax.swing.JMenu();
        jmiAgregarCliente = new javax.swing.JMenuItem();
        jmiBorrarCliente = new javax.swing.JMenuItem();
        jmBuscarCliente = new javax.swing.JMenu();
        jmiBuscarClientePorTelefono = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Directorio de telefonos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jmEditarCliente.setText("Editar cliente");
        jmEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarClienteActionPerformed(evt);
            }
        });

        jmiAgregarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jmiAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        jmiAgregarCliente.setText("Agregar cliente");
        jmiAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarClienteActionPerformed(evt);
            }
        });
        jmEditarCliente.add(jmiAgregarCliente);

        jmiBorrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jmiBorrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        jmiBorrarCliente.setText("Borrar cliente");
        jmiBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarClienteActionPerformed(evt);
            }
        });
        jmEditarCliente.add(jmiBorrarCliente);

        jmbMenu.add(jmEditarCliente);

        jmBuscarCliente.setText("Buscar cliente");
        jmBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmBuscarClienteMouseClicked(evt);
            }
        });
        jmBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBuscarClienteActionPerformed(evt);
            }
        });

        jmiBuscarClientePorTelefono.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jmiBuscarClientePorTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lupa miniatura.png"))); // NOI18N
        jmiBuscarClientePorTelefono.setText("Buscar cliente por telefono");
        jmiBuscarClientePorTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiBuscarClientePorTelefonoMouseClicked(evt);
            }
        });
        jmiBuscarClientePorTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarClientePorTelefonoActionPerformed(evt);
            }
        });
        jmBuscarCliente.add(jmiBuscarClientePorTelefono);

        jmbMenu.add(jmBuscarCliente);

        jmSalir.setText("Salir");
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });

        jmiSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmSalir.add(jmiSalir);

        jmbMenu.add(jmSalir);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        viewAgregarCliente ac = new viewAgregarCliente(directorio);
        ac.setVisible(true);
        escritorio.add(ac);
        escritorio.moveToFront(ac);
    }//GEN-LAST:event_jmiAgregarClienteActionPerformed

    private void jmEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarClienteActionPerformed
        
    }//GEN-LAST:event_jmEditarClienteActionPerformed

    private void jmiBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        viewBorrarCliente borrarCliente = new viewBorrarCliente(directorio);
        borrarCliente.setVisible(true);
        escritorio.add(borrarCliente);
        escritorio.moveToFront(borrarCliente);
    }//GEN-LAST:event_jmiBorrarClienteActionPerformed

    private void jmBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBuscarClienteActionPerformed
        
    }//GEN-LAST:event_jmBuscarClienteActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
     
    }//GEN-LAST:event_jmSalirActionPerformed

    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
       
    }//GEN-LAST:event_jmSalirMouseClicked

    private void jmBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmBuscarClienteMouseClicked
        
    }//GEN-LAST:event_jmBuscarClienteMouseClicked

    private void jmiBuscarClientePorTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiBuscarClientePorTelefonoMouseClicked

    }//GEN-LAST:event_jmiBuscarClientePorTelefonoMouseClicked

    private void jmiBuscarClientePorTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarClientePorTelefonoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();

        viewBuscarCliente buscarCliente = new viewBuscarCliente(directorio);
        buscarCliente.setVisible(true);
        escritorio.add(buscarCliente);
        escritorio.moveToFront(buscarCliente);
    }//GEN-LAST:event_jmiBuscarClientePorTelefonoActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
       dispose();
    }//GEN-LAST:event_jmiSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jmBuscarCliente;
    private javax.swing.JMenu jmEditarCliente;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiAgregarCliente;
    private javax.swing.JMenuItem jmiBorrarCliente;
    private javax.swing.JMenuItem jmiBuscarClientePorTelefono;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}
